CREATE TABLE problems (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    title VARCHAR(255) NOT NULL,

    description_md LONGTEXT NOT NULL,

    difficulty ENUM('EASY', 'MEDIUM', 'HARD') NOT NULL,

    tags VARCHAR(255),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);