spring.application.name=codearena

spring.datasource.url=jdbc:mysql://localhost:3306/codearena?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
# spring.flyway.clean-on-migrate=false
spring.flyway.validate-on-migrate=false

jwt.secret=ZmYzY2Q2MjNhMWQ2YjIyODQ5MzQ0ZjE4ZmU2YmYxM2MzODNmYjVmODQ1NTEzMmE0NTY0ZDYxYjYzMzM2NTM0Yw==
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile